import { useState, type RefObject } from "react";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { Input } from "../../components/ui/Input";
import type { FollowupDraft, Lead } from "./crm-types";

export function FollowupDialog({ lead, triggerRef, onClose, onSubmit }: { lead: Lead | null; triggerRef?: RefObject<HTMLElement | null>; onClose: () => void; onSubmit: (lead: Lead, input: FollowupDraft) => Promise<void> }) {
  const [type, setType] = useState<FollowupDraft["type"]>("CALL"); const [dueAt, setDueAt] = useState(""); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Dialog open={Boolean(lead)} title="Agendar follow-up" description={lead ? `Próximo contato com ${lead.name}.` : undefined} onClose={onClose} triggerRef={triggerRef} size="sm"><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); if (!lead) return; const date = new Date(dueAt); if (!dueAt || !Number.isFinite(date.getTime())) return setError("Informe uma data e hora válidas."); if (date.getTime() <= Date.now()) return setError("O follow-up deve ser agendado para o futuro."); setBusy(true); setError(""); void onSubmit(lead, { type, dueAt: date.toISOString(), notes: notes.trim() || undefined }).then(onClose).catch(() => setError("Não foi possível agendar o follow-up.")).finally(() => setBusy(false)); }}>{error && <p role="alert" className="text-red-300">{error}</p>}<div className="grid gap-2"><label htmlFor="followup-type" className="font-semibold">Tipo</label><select id="followup-type" className="min-h-11 rounded-lg border border-border bg-surface-base px-3" value={type} onChange={(event) => setType(event.target.value as FollowupDraft["type"])}><option value="CALL">Ligação</option><option value="EMAIL">E-mail</option><option value="MESSAGE">Mensagem</option></select></div><Input label="Data e hora" type="datetime-local" required value={dueAt} onChange={(event) => setDueAt(event.target.value)} /><div className="grid gap-2"><label htmlFor="followup-notes" className="font-semibold">Notas</label><textarea id="followup-notes" className="min-h-28 rounded-lg border border-border bg-surface-base p-3" value={notes} onChange={(event) => setNotes(event.target.value)} /></div><div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit" loading={busy}>Agendar</Button></div></form></Dialog>;
}
