import { useEffect, useState, type RefObject } from "react";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import type { Lead, LeadStage, Pipeline } from "./crm-types";

export function LostReasonDialog({ lead, stage, reasons, triggerRef, onClose, onConfirm }: { lead: Lead | null; stage: LeadStage | null; reasons: Pipeline["lossReasons"]; triggerRef?: RefObject<HTMLElement | null>; onClose: () => void; onConfirm: (reasonCode: string, notes: string) => Promise<void> }) {
  const [code, setCode] = useState(""); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (lead) { setCode(""); setNotes(""); setError(""); } }, [lead]);
  return <Dialog open={Boolean(lead && stage)} title="Registrar perda do lead" description="Informe o motivo antes de mover para Perdido." onClose={onClose} triggerRef={triggerRef} size="sm"><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); if (!code || !notes.trim()) return setError("Selecione o motivo e informe a justificativa."); setBusy(true); setError(""); void onConfirm(code, notes.trim()).then(onClose).catch(() => setError("Não foi possível mover o lead.")).finally(() => setBusy(false)); }}>{error && <p role="alert" className="text-red-300">{error}</p>}<div className="grid gap-2"><label htmlFor="loss-reason" className="font-semibold">Motivo padronizado</label><select id="loss-reason" required className="min-h-11 rounded-lg border border-border bg-surface-base px-3" value={code} onChange={(event) => setCode(event.target.value)}><option value="">Selecione</option>{reasons.map((reason) => <option key={reason.code} value={reason.code}>{reason.label}</option>)}</select></div><div className="grid gap-2"><label htmlFor="loss-notes" className="font-semibold">Justificativa</label><textarea id="loss-notes" required minLength={3} className="min-h-28 rounded-lg border border-border bg-surface-base p-3" value={notes} onChange={(event) => setNotes(event.target.value)} /></div><div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit" variant="danger" loading={busy}>Confirmar perda</Button></div></form></Dialog>;
}
