import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { useEffect, useState, type RefObject } from "react";
import { Button } from "../../components/ui/Button";
import { Dialog } from "../../components/ui/Dialog";
import { Input } from "../../components/ui/Input";
import type { LeadStage } from "./crm-types";

type StageDraft = { key: string; id?: string; version?: number; name: string; position: number; color: string; outcome?: LeadStage["outcome"]; removable: boolean };
const CANONICAL_STAGE_CODES = new Set(["NEW", "QUALIFIED", "MEETING_SCHEDULED", "PROPOSAL_SENT", "WON", "LOST"]);

export function StageCustomizationDialog({ open, stages, triggerRef, onClose, onSubmit }: { open: boolean; stages: LeadStage[]; triggerRef?: RefObject<HTMLElement | null>; onClose: () => void; onSubmit: (stages: Array<{ id?: string; version?: number; name: string; position: number; color: string }>) => Promise<void> }) {
  const [draft, setDraft] = useState<StageDraft[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) { setDraft([...stages].sort((a, b) => a.position - b.position).map((stage) => ({ key: stage.id, id: stage.id, version: stage.version, name: stage.name, position: stage.position, color: stage.color, outcome: stage.outcome, removable: !CANONICAL_STAGE_CODES.has(stage.code) }))); setError(""); } }, [open, stages]);
  function move(index: number, offset: number) { setDraft((current) => { const copy = [...current]; const target = index + offset; if (target < 0 || target >= copy.length) return current; [copy[index], copy[target]] = [copy[target]!, copy[index]!]; return copy; }); }
  async function submit() { setBusy(true); setError(""); try { await onSubmit(draft.map((stage, index) => ({ ...(stage.id ? { id: stage.id, version: stage.version } : {}), name: stage.name, position: index + 1, color: stage.color }))); onClose(); } catch { setError("Não foi possível salvar as etapas. Atualize e tente novamente."); } finally { setBusy(false); } }
  return <Dialog open={open} title="Personalizar etapas" description="Altere nomes, cores e ordem do pipeline global." onClose={onClose} triggerRef={triggerRef}><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); void submit(); }}>{error && <p role="alert" className="text-red-300">{error}</p>}{draft.map((stage, index) => <fieldset key={stage.key} className="grid gap-3 rounded-lg border border-border-subtle p-4 sm:grid-cols-[1fr_8rem_auto]"><legend className="sr-only">Etapa {stage.name}</legend><Input label="Nome" value={stage.name} onChange={(event) => setDraft((current) => current.map((item) => item.key === stage.key ? { ...item, name: event.target.value } : item))} required /><Input label="Cor" type="color" className="p-1" value={stage.color} onChange={(event) => setDraft((current) => current.map((item) => item.key === stage.key ? { ...item, color: event.target.value } : item))} /><div className="flex items-end"><Button type="button" variant="ghost" className="px-3" aria-label={`Mover ${stage.name} para cima`} disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp aria-hidden="true" /></Button><Button type="button" variant="ghost" className="px-3" aria-label={`Mover ${stage.name} para baixo`} disabled={index === draft.length - 1} onClick={() => move(index, 1)}><ArrowDown aria-hidden="true" /></Button>{stage.outcome === "OPEN" && stage.removable && <Button type="button" variant="ghost" className="px-3" aria-label={`Remover ${stage.name}`} onClick={() => setDraft((current) => current.filter((item) => item.key !== stage.key))}><Trash2 aria-hidden="true" /></Button>}</div></fieldset>)}<Button type="button" variant="secondary" className="justify-self-start" onClick={() => setDraft((current) => [...current, { key: crypto.randomUUID(), name: "Nova etapa", color: "#64748b", position: current.length + 1, outcome: "OPEN", removable: true }])}><Plus aria-hidden="true" />Adicionar etapa</Button><p className="text-sm text-brand-100">Etapas canônicas e etapas com leads não podem ser removidas.</p><div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit" loading={busy}>Salvar etapas</Button></div></form></Dialog>;
}
